# Generated by Django 5.0.1 on 2024-06-08 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, unique=True)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Features', models.TextField()),
                ('Target', models.TextField()),
                ('Instructor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
