# Generated by Django 5.0.1 on 2024-06-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Duration',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
