# Generated by Django 5.0.1 on 2024-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_contactus_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
